# Generated by Django 5.2.8 on 2026-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
