# Generated by Django 5.2.8 on 2026-09-17 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_assigned_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_scores', models.JSONField(default=dict)),
                ('recent_product_ids', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
