# Generated by Django 5.2.8 on 2026-09-14 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('sole_proprietor', 'Sole Proprietor'), ('partnership', 'Partnership'), ('limited_company', 'Limited Company'), ('other', 'Other')], max_length=20)),
                ('business_reg_no', models.CharField(blank=True, max_length=100)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('product_categories', models.TextField(help_text='Categories/products they intend to sell')),
                ('monthly_volume', models.CharField(blank=True, help_text='Expected monthly sales volume', max_length=100)),
                ('experience', models.TextField(blank=True, help_text='Trading/business experience')),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trader_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trader_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
