# Generated by Django 5.2.8 on 2026-09-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_returnrequest'),
        ('traders', '0004_traderproduct_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader_status', to='orders.orderitem')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='traders.traderapplication')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('trader', 'order_item')},
            },
        ),
    ]
