# Generated by Django 5.2.8 on 2026-09-15 06:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0005_traderorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderapplication',
            name='bio',
            field=models.TextField(blank=True, help_text='Short business description shown on store'),
        ),
        migrations.AddField(
            model_name='traderapplication',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Trader has closed their shop (soft close)'),
        ),
        migrations.AddField(
            model_name='traderapplication',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='If False, all trader products are hidden from store'),
        ),
        migrations.AddField(
            model_name='traderapplication',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
