# Generated by Django 5.2.8 on 2026-09-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0006_traderapplication_bio_traderapplication_is_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='traders.traderproduct')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='traders.traderapplication')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('trader', 'product')},
            },
        ),
        migrations.CreateModel(
            name='TraderStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjust', 'Adjustment'), ('return', 'Return')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='traders.traderinventoryitem')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='traders.traderapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
