# Generated by Django 5.2.8 on 2026-09-17 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0007_traderinventoryitem_traderstockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traderorderitem',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trader_order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
