from django.urls import path
from .views import (
    AccountingDashboardView,
    SupplierListCreateView, SupplierDetailView,
    PurchaseListCreateView, PurchaseDetailView,
    ExpenseCategoryListCreateView, ExpenseListCreateView, ExpenseDetailView,
    AccountListCreateView, AccountDetailView, AccountTransferListCreateView,
    ReceivableListCreateView, ReceivableDetailView,
    PayableListCreateView, PayableDetailView,
    TaxRecordListCreateView, TaxRecordDetailView,
    RefundListCreateView, RefundDetailView,
    EmployeeListCreateView, EmployeeDetailView,
    FixedAssetListCreateView, FixedAssetDetailView,
    AuditLogListView,
)

urlpatterns = [
    path('dashboard/', AccountingDashboardView.as_view()),
    path('suppliers/', SupplierListCreateView.as_view()),
    path('suppliers/<int:pk>/', SupplierDetailView.as_view()),
    path('purchases/', PurchaseListCreateView.as_view()),
    path('purchases/<int:pk>/', PurchaseDetailView.as_view()),
    path('expense-categories/', ExpenseCategoryListCreateView.as_view()),
    path('expenses/', ExpenseListCreateView.as_view()),
    path('expenses/<int:pk>/', ExpenseDetailView.as_view()),
    path('accounts/', AccountListCreateView.as_view()),
    path('accounts/<int:pk>/', AccountDetailView.as_view()),
    path('transfers/', AccountTransferListCreateView.as_view()),
    path('receivables/', ReceivableListCreateView.as_view()),
    path('receivables/<int:pk>/', ReceivableDetailView.as_view()),
    path('payables/', PayableListCreateView.as_view()),
    path('payables/<int:pk>/', PayableDetailView.as_view()),
    path('taxes/', TaxRecordListCreateView.as_view()),
    path('taxes/<int:pk>/', TaxRecordDetailView.as_view()),
    path('refunds/', RefundListCreateView.as_view()),
    path('refunds/<int:pk>/', RefundDetailView.as_view()),
    path('employees/', EmployeeListCreateView.as_view()),
    path('employees/<int:pk>/', EmployeeDetailView.as_view()),
    path('assets/', FixedAssetListCreateView.as_view()),
    path('assets/<int:pk>/', FixedAssetDetailView.as_view()),
    path('audit/', AuditLogListView.as_view()),
]
