# Generated by Django 5.2.8 on 2026-09-17 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_trader'),
        ('traders', '0007_traderinventoryitem_traderstockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trader_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_product', to='traders.traderproduct'),
        ),
    ]
